spring.application:
  name: java-sticky-loadbalancer
spring.liquibase.enabled: true
spring.liquibase.change-log:
    classpath:db/changelog/db.changelog-master.yaml
spring.datasource:
  url: jdbc:h2:tcp://localhost:4000/sticky-lb.db
  driverClassName: org.h2.Driver
  username: sa
  password:
spring.threads.virtual.enabled:
    true

spring:
    jms:
        listener:
            acknowledge-mode: auto
            auto-startup: true
            concurrency: 1
